### ISSUE TITLE
Twitter service does not account for URLs in the message

### ISSUE THREAD

**Issue by annevk** [github/github-services#964]
See e.g. https://twitter.com/encodings/status/528586451504463872 having truncated URL in it that therefore points to the wrong bug.

**Comment by kdaigle** [comment]
We rely on Twitter to shorten URLs using their shortener. You can read more in the [Twitter service](https://github.com/github/github-services/blob/master/lib/services/twitter.rb). There have also been other bugs solved around this area since this issue so it is likely this is already fixed.

**Comment by annevk** [comment]
The problem is that truncated URLs get shortened. And no this is not fixed. Could you please reopen this? Recent example: https://twitter.com/urlstandard/status/632595525796253696

**Comment by kdaigle** [comment]
Hey @annevk! Yup, I'll re-open this issue. Thanks for adding more information to this issue.

**Comment by stof** [comment]
The issue is that you truncate the commit message yourselves to fit within the 140 char limit, but you don't account for URLs in the commit message which would be shorted, and so should not count for their own length but for the t.co length (you take it into account only for the URL you are adding yourselves): https://github.com/github/github-services/blob/f804613a178f0f46acc53eded85308d5db25929a/lib/services/twitter.rb#L58

**Comment by keavy** [comment]
Thanks for clarifying @stof :zap:

We'd be happy to look at a PR [that implements a bug fix](https://github.com/github/github-services/blob/master/CONTRIBUTING.md#updating-an-existing-service) for this.

**Comment by stof** [comment]
Well, the logic implementing the computation of the tweet length is available in https://github.com/twitter/twitter-text/blob/6f7eef096abb10b17d43a391b637fc494877ae21/rb/lib/twitter-text/validation.rb#L13-L36
I don't know whether you would consider using this library to compute it.
In any case, I will let someone else work on this. I'm a PHP developer, not a Ruby one

**Comment by mikemcquaid** [comment]
We'd probably rather this is done without adding another library. If anyone wants to try and create a pull request (or needs help) feel free to ask.

**Comment by mikemcquaid** [comment]
We may accept a PR that doesn't use another library but I'm closing this out for now.
